### ISSUE TITLE
Wrong role used when two posters have same nick

### ISSUE THREAD

**Issue by wstephenson** [post-tracker/site#13]
Since a recent update, posts on elitedevtracker show the incorrect role for Adam Woods ("Designer").  Apparently the tracker is taking this role from Adam Waite, who coincidentally shares the same nick value 'Adam'.

**Comment by kokarn** [comment]
Shit! 
Yeah, that's my bad. 
It also probably meant that the posts from the RSS weren't showing for either of the Adams.

Thanks for reporting! Should be working as expected when the update hits the live server.
