### ISSUE TITLE
ARK account update

### ISSUE THREAD

**Issue by LandDragoon** [post-tracker/site#21]
I couldn't find the file where you define the accounts for the devs, so here's an issue instead.
One of the ARK devs (Casanova) has changed his Twitter account from explore_ark to [CudaCores](https://twitter.com/CudaCores). Maybe it's also better to rename him to Chris, as I guess that more people know him by that name than Casanova.

**Comment by kokarn** [comment]
Hey!
Yeah that stuff's been moved to the API so I can keep the repos a bit more pure :)

Thanks for the update!
Added CudaCores and changed Casanova's name to Chris.
