### ISSUE TITLE
R6 Tracker Link broken?

### ISSUE THREAD

**Issue by DevJPM** [post-tracker/site#24]
Hi,

when I follow the link "https://devtracker.kokarn.com/rainbow6" as supplied in the R6 subreddit and in the promoted readme, I receive an HSTS certificate error claiming that the server served a certificate for "developertracker.com".

Now I've learned that apparently you moved the tracker to "https://developertracker.com/rainbow6/".

I suspect the issue is caused by a combination of a) enabling HSTS, b) adding a 301 redirect (or something) to the original site and c) the caching behavior by browsers.

Can you now please confirm that you have moved the tracker to the new URL and that this should be used as the authoritative link in the future?

Oh and can you please update your Readme if this is the case? ;)

(I'll try and forward any information gathered here to the R6 subreddit mods)

**Comment by kokarn** [comment]
Correct, I've moved it. 
Sorry I didn't make sure the old url still worked as intended, just assumed it would.

I'll updated the README and try to fix so there is a redirect :)

Anything else I can do for you?

**Comment by DevJPM** [comment]
No, that would be about everything.

Note that if people get the certificate error, a HTTP redirect won't work as they won't load the HTTP but error out at the handshake before that, so if you can be bothered, please setup the appropriate (LE) cert for the old domain.

I'll now try and reach out to the R6 subreddit mods so they can replace the link :)

Thank you for the quick response.

**Comment by kokarn** [comment]
You are of course correct about the redirect but not sure I'll do anything more to fix it.
It's actually the only url served over that domain so there shouldn't be many hits after the links on Reddit and in the README are changed.

I'll check but no promises ;)

Anything else I can do for you?

**Comment by DevJPM** [comment]
No, that's all. Thank you very much :)
