### ISSUE TITLE
Heads Up - Future change to miggy.org RSS feed for full text of posts.

### ISSUE THREAD

**Issue by Athanasius** [post-tracker/site#29]
I've recently been doing some work to scrap the full text of forum posts, including any quotes etc.  Currently I have this additional scraping running but am still outputting only the 'precis' from the Activity Lists.  At some point in the future I'll switch the output over to the fulltext version.

So, just wanted to give you a heads up and URL of an example RSS file so you can see what the output will be like: https://miggy.org/games/elite-dangerous/devtracker-dev/ed-dev-posts-fulltext-example.rss

Checking with my own Tiny Tiny RSS installation, and also Feedly, it's common to strip off **all** the attributes of the HTML elements inside `<description>...</description>` so I'm trying not to rely on any such.  This means I can't use a style="..." attribute to make things look like they do on the forums, so I'm not even trying.

What's still in the output is simply copied from the forums so users can utilise it in output styling it they so wish.  Due to the TTRSS/Feedly restrictions I've so far implemented changing the 'quote' `<div>` class from the forums into a `blockquote` element instead.  Before that I also strip out the `blockquote` that the forums use to wrap the entire post (comment/reply) body.

I still need to experiment to see if I can do anything sane with a `[code]` element from the forums, likely changing relevant `<div>` elements into `<pre>` ones.

If you want to check the code it's at https://github.com/Athanasius/ed-devtracker - I did the initial work in the 'fulltext' branch, but that's now been merged into master.  Changing the output is a simple config flag so can be done at any time.

**Comment by kokarn** [comment]
Hey! Thanks for the heads up.

I've actually been following the repo for a while so I'm very excited about this.
The parsing you mention will probably work right out of the box but I'll try to have a look ASAP so we don't break anything too badly.

Are you planning on implementing the full BBCode spec or just the parts you happen to run into?

I did something similar for one of my other [indexers recently](https://github.com/post-tracker/indexer/blob/master/src/modules/BBCode.js) so I know it's a bit rough to get something that works great for all cases...

Great work on the indexer btw, and love that you are sharing your work.

**Comment by Athanasius** [comment]
Ah, I'm not actually parsing any BB**code** at all, only the resultant HTML.  Take a look at the first `<item>` in the example RSS file above, you'll see it's mostly a bunch of `<div>`s with specific classes.  

Any styling in the HTML will be preserved in my output, excepting what I described above about changing the `<blockquote>` (which isn't actually styled as such on the forums) into a `<div>` and then changing actual 'quote' `<div>`s into `<blockquote>`s instead.  Worst case scenario for `[code]` will be that I just leave the HTML as it's given by the forums, meaning a `<div>`.

Anything else like `<i>` would just be left as-is in the HTMl output.  I'm stripping the image references used for emoticons though as they upset both RSS feed validation and TTRSS.

**Comment by Athanasius** [comment]
The current full extent of the munging on output I do is at https://github.com/Athanasius/ed-devtracker/blob/fulltext/ED/DevTracker/RSS.pm#L113-L147

**Comment by kokarn** [comment]
Cool, looks very good!

Tried the output now myself and everything looks great, except for a bunch of `\n` that happen to be in the feed. https://i.imgur.com/Vxn3Wpq.png

Are you planning on keeping them as is or will you parse them in any way?
Trying to figure out what the standard says if it's anything at all but can't really find anything.

**Comment by Athanasius** [comment]
And this is why I wanted to give a heads-up :).

Being just white space anything I'm testing things in is swallowing them.  I'll take a closer look and see if I can do something sensible with them.  Could you re-purpose your comment as a new issue on my repo please ?

**Comment by Athanasius** [comment]
Firstly I've opened an issue on my repo about this myself.

Thinking about this more, whatever you have rendering that output is obviously interpreting HTML, so why is it not just ignoring the \n characters like any other HTML renderer does ?  Explicitly rendering them as `\n` seems very strange.  I'd expect them to either be ignored or converted to (extra) `<br/>`.

There are some stray `ctrl-M` characters (\\r) in there that I might see about stripping out though.

**Comment by Athanasius** [comment]
In fact checking the current live RSS feed it has `\n` characters throughout most `<description>` elements as well, so presumably you'd already been seeing this issue ?  If there's a difference it will be to do with their association with `<p>` elements.

**Comment by kokarn** [comment]
Seems you are correct. I did a lazy comparison by just running the indexer and then inserting the contents into the page at the right place. This seems to have not fully rendered it but instead only rendered the HTML.

So the fault is completely on my end.
Thanks for looking into it tho

**Comment by Athanasius** [comment]
There's now an additional live feed with the fulltext in items: https://miggy.org/games/elite-dangerous/devtracker/ed-dev-posts-fulltext.rss

At this point I don't plan to change the old URL, so if you want to use the fulltext you'll need to test and switch to this new URL.

**Comment by kokarn** [comment]
Finally implemented live!

Thanks for the heads up, sorry I was so slow.
