### ISSUE TITLE
How the heck!

### ISSUE THREAD

**Issue by ghost** [post-tracker/site#30]
How the hell do I run this? I had the last one running fine on my site, What does this require?

**Comment by kokarn** [comment]
Which one is "the last one" ?
This has been split up into multiple indexers, an API and the site that acts as the front-end.

What are you trying to accomplish?

**Comment by ghost** [comment]
I am trying to setup the ark Dev tracker, A while back It was working but now when I set this up on a new web server. Nothing but 3 icons show

**Comment by kokarn** [comment]
Yeah, you need to start the API and the indexers as well with the current version.

**Comment by ghost** [comment]
Care to give a quick tutorial on how to do this ?

**Comment by kokarn** [comment]
Yeah, I should do that.

But basically, you need the indexer and the rest API running. And then you build the site pointing to the API.

**Comment by ghost** [comment]
Yep no idea how :P

**Comment by kokarn** [comment]
You need somewhere to run the API & Indexer. You can clone them both and start with pm2, that's pretty straightforward. You also need a database on the server running the API.

For the site you can start a basic version with the incorporated dev-server and just configure the path for the API.

I'm a bit curious, why are you trying to do this? Just wanna test it out?

**Comment by ghost** [comment]
I try to do anything and everything. Learning by doing. I also want to have my own version integrated within a project im working on for ARK.

**Comment by kokarn** [comment]
Then i'd suggest using the API for arkdevtracker.com and just running the site :)

**Comment by ghost** [comment]
When I tried to set that up, I only got the header, everything else below it was white.

Do you have another method we could use to communicate? Discord / Steam ?

**Comment by kokarn** [comment]
Sure, hit me up on discord.

**Comment by ghost** [comment]
Where is your Info ?

**Comment by kokarn** [comment]
Should be just kokarn@gmail.com or kokarn :)
