### ISSUE TITLE
Add new Elite community manager

### ISSUE THREAD

**Issue by wstephenson** [post-tracker/site#37]
https://twitter.com/monsieurwillie

https://forums.frontier.co.uk/member.php/170935-Will-Flanagan

**Comment by kokarn** [comment]
Thanks for reporting this!

I actually added him yesterday but forgot to add the MiggyRSS identifier and didn't find the twitter account.

They've both been added now. Thank you so much!

**Comment by wstephenson** [comment]
You're welcome, keep providing a great service!

**Comment by kokarn** [comment]
Thanks for the kind words.
Doing my best!
