### ISSUE TITLE
Update known Anthem developers on Reddit.

### ISSUE THREAD

**Issue by Wobbley** [post-tracker/site#44]
Hey

Do you use the flair or usernames to identify developer posts? I assume it is the latter since the Reddit tracker seems to be out of date. 

I am one of the /r/Anthemthegame subreddit mods, here is our list of the known developers:
https://docs.google.com/spreadsheets/d/1TBam58H4reNwaHLXwnDAH9muVkIxMNa077n3kF_GGBM/edit?usp=sharing

If you want to reach me I am @Wobbley on the Anthem Discord or Reddit

**Comment by kokarn** [comment]
Thank you for this! All the devs have been added and updated where applicable.
