### ISSUE TITLE
Update devs for ARK: Survival Evolved

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [post-tracker/site#48]
Hi there,
Since many devs from ARK have moved to the new ATLAS project, the ark dev tracker should be updated to include the relevant people.
Thanks!

**Comment by kokarn** [comment]
Hello! 

Yes, this seems like something that I should do. Do you by any chance know what devs have moved over? I'm a bit tight on time to check them out at the moment.

**Comment by rodrigoalcarazdelaosa** [comment]
Hi!
Have you got a list of the devs currently tracked for https://arkdevtracker.com? I know for certain that [Jat](https://twitter.com/jatheish?lang=es), [Jesse](https://twitter.com/arkjesse?lang=es) and [Jeremy](https://twitter.com/jeremystieglitz?lang=es) have moved to ATLAS. These people should actually be tracked in a new ATLAS tracker. [Chris](https://twitter.com/cudacores?lang=es) is working in ATLAS too.

[Chris Willoughby](https://twitter.com/arkchrisw) is the new Lead Programmer on ARK and [Jen](https://twitter.com/bubblywums?lang=es) is still the main community manager for ARK.

**Comment by mobiCompete** [comment]
Jesse and Jeremy are still providing the creative direction for ARK so it may be worth leaving them. Chris is the web developer for both playatlas.com and survivetheark.com so he should be left as well.

**Comment by chdavi** [comment]
A couple of things. Jesse and Jeremy are still providing the creative direction for ARK so it might be worth leaving them.  

Chris also is the web developer for both survivetheark.com and playatlas.com. If we remove him we will lose notifications about the site being down.

**Comment by mobiCompete** [comment]
Was this meant for me or another Chris?

Sent from my iPhone

On Dec 31, 2018, at 7:54 PM, Christopher Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


A couple of things. Jesse and Jeremy are still providing the creative direction for ARK so it might be worth leaving them.

Chris also is the web developer for both survivetheark.com<http://survivetheark.com> and playatlas.com<http://playatlas.com>. If we remove him we will lose notifications about the site being down.

**Comment by rodrigoalcarazdelaosa** [comment]
Agree. Only Jat should be removed then?

Enviado desde mi iPhone

**Comment by chdavi** [comment]
I think evilmrfrank should be removed as well. He is working on Atlas.

**Comment by Flachdachs** [comment]
Please remove Jat asap. He is cluttering the ARK Dev Tracker. He never wrote that many posts in the time he was working for the Ark project.

**Comment by kokarn** [comment]
Sorry for this taking so long!

I've removed Jat & evilmrfrank.

If I'm missing someone, please let me know
