### ISSUE TITLE
How can I get a RSS of the Elite dangerous tracker without Twitter posts?

### ISSUE THREAD

**Issue by Noodles4Pasta** [post-tracker/site#51]
It seems that the Devs twitter feed in this tracker floods it with their personal posts... so I am hoping to get a more Elite related feed by excluding that, but I dont see an option for that. Please tell me if there is some way to change this so I can use it for our members. Thanks!

**Comment by kokarn** [comment]
The RSS should be without twitter posts as is.

PS: Sorry for the slow reply
