### ISSUE TITLE
ARK dev tracker needs an update

### ISSUE THREAD

**Issue by toto2917** [post-tracker/site#57]
Hi!

The dev list needs an update. (Tags below are Twitter tags)

@KaydHendricks  "The Right Hand"
https://twitter.com/KaydHendricks
He is now working on ATLAS and doesn't tweet about his work on the game, he's just announcing his personnal livestreams on Twitch. He should be removed.

@CraigBCBrown
https://twitter.com/CraigBCBrown
He is now working on ARK, so new dev. He is Senior Designer and tweets sometimes about ARK. He should be added.

@SeggzyGaming 
https://twitter.com/SeggzyGaming
He is working on ARK and doesn't appear on the tracker, he should be added. He is Lead QA Analyst.

@Skittlis 
https://twitter.com/Skittlis
He's also working on ARK and doesn't appear on the tracker, he should be added. He is QA Analyst.

@KeenAspect 
https://twitter.com/KeenAspect
He's the Producer of ARK and doesn't appear on the tracker, he should be added. 

Thanks!

**Comment by kokarn** [comment]
Sorry for the late reply!

All changes have been made as requested. You don't happen to have any accounts on survivetheark?

Thanks for reaching out and helping me keep the quality of the site :)

**Comment by toto2917** [comment]
Oh, you can track posts on survivetheark? If so, here's CM's account: https://survivetheark.com/index.php?/profile/1109745-cedric/

**Comment by kokarn** [comment]
Added!
