### ISSUE TITLE
Add Dollie to arkdevtracker please

### ISSUE THREAD

**Issue by Elgar82** [post-tracker/site#58]
Hi,

Dollie should be added to arkdevtracker because recently a lot of informations about ARK / Genesis came from her.

See her twitter account : https://twitter.com/notdollie

And Community Manager Cedric confirmed in a tweet 2 days ago that we'll see her a lot more. Source : https://twitter.com/ComplexMinded/status/1232854152604028928

**Comment by kokarn** [comment]
Thanks for reaching out! It's been done. You don't happen to know if she has an account on survivetheark?
