### ISSUE TITLE
 ARK dev tracker needs (another) update

### ISSUE THREAD

**Issue by alessiot89** [post-tracker/site#68]
I don't see Jeremy Stieglitz twitter updates. He is: "Co-showrunner ARK: The Animated Series. Lead designer/programmer & cocreative director of ARK: Survival Evolved, cofounder StudioWildcard."

I only found his twitter account: https://twitter.com/jeremystieglitz

**Comment by alessiot89** [comment]
ARK nintendo switch twitter account: https://twitter.com/PlayARKSwitch

**Comment by alessiot89** [comment]
GG Fizz is now QA Analyst at Studio Wildcard  https://twitter.com/GGFizz41
Hes account should be added too.

**Comment by kokarn** [comment]
Thanks for all these updates! 

All of them have been added & updated and should start showing up :)
